import "WindowsSearchResult.idl";

namespace WindowsSearch
{
    [bindable]
    [default_interface]
    static runtimeclass WindowsSearcher 
    {
        static WindowsSearchResult GetFiles(String folderPath);
    }
}
