namespace NfqReplacementLib
{
    [bindable]
    [default_interface]
    runtimeclass FileSystemItem 
    {
        FileSystemItem();

        String Name{ get; set;  };
        String Path{ get; set; };

        String Type{ get; set; };
        Windows.Foundation.DateTime DateModified{ get; set; };
        Windows.Foundation.DateTime DateCreated{ get; set; };
        UInt64 Size{ get; set; };

        Windows.Foundation.DateTime ItemDate{ get; set; };
        Windows.Foundation.DateTime DateTaken{ get; set; };
        String Dimensions{ get; set; };
        Windows.Foundation.Collections.IVector<String> Tags{ get; set; };
        UInt32 Rating{ get; set; };
    }
}
