import "WindowsSearchResultStatus.idl";
import "FileSystemItem.idl";

namespace NfqReplacementLib
{
    [bindable]
    [default_interface]
    runtimeclass WindowsSearchResult 
    {
        WindowsSearchResult(WindowsSearchResultStatus status);
        WindowsSearchResult(WindowsSearchResultStatus status, Windows.Foundation.Collections.IVector<FileSystemItem> items);

        WindowsSearchResultStatus Status{ get; };
        Windows.Foundation.Collections.IVector<FileSystemItem> Items{ get; };
    }
}
