namespace FileSystem
{
    [bindable]
    [default_interface]
    runtimeclass FileExplorerSort
    {
        FileExplorerSort(String propertyKey, Boolean ascending);
        String PropertyKey{ get; };
        Boolean Ascending{ get; };
    }
}
