import "WindowsSearchResult.idl";

namespace FileSystem
{
    [bindable]
    [default_interface]
    static runtimeclass WindowsSearch 
    {
        static WindowsSearchResult GetFiles(String folderPath);
    }
}
